//
//  CardDetailViewController.swift
//  HearthstoneLegendaryAPI
//
//  Created by 18579118 on 29.07.2020.
//  Copyright (c) 2020 18579118. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CardDetailViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: CardDetailPresenterInterface!
    
    // MARK: - private properties -
    var cardImage = UIImageView()
    var cardDescription = UILabel()
    
    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

}

// MARK: - Extensions -

extension CardDetailViewController: CardDetailViewInterface {
    func setView() {
        
    }
    
    func setConstraints() {
        
    }
}
