//
//  CardDetailPresenter.swift
//  HearthstoneLegendaryAPI
//
//  Created by 18579118 on 29.07.2020.
//  Copyright (c) 2020 18579118. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CardDetailPresenter {

    // MARK: - Private properties -
    private enum Constants {
        static let defaultUrl = ""
    }
    private unowned let view: CardDetailViewInterface
    private let interactor: CardDetailInteractorInterface
    private let wireframe: CardDetailWireframeInterface

    // MARK: - Lifecycle -

    init(view: CardDetailViewInterface, interactor: CardDetailInteractorInterface, wireframe: CardDetailWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension CardDetailPresenter: CardDetailPresenterInterface {
    func configureView() {
        view.setView()
        view.setConstraints()
        let card = interactor.cards
        let urlString = card.image
        guard let url = URL(string: urlString) else {
            view.cardDescription.text = card.flavorText
            return
        }
        view.cardImage.load(url: url)
        view.cardDescription.text = card.flavorText
        view.cardDescription.textColor = .magenta
    }
    
    func move() {
        wireframe.moveTo(withStringUrl: interactor.cards.imageGold ?? Constants.defaultUrl)
    }
}
