//
//  CardDetailInteractor.swift
//  HearthstoneLegendaryAPI
//
//  Created by 18579118 on 29.07.2020.
//  Copyright (c) 2020 18579118. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CardDetailInteractor {
}

// MARK: - Extensions -

extension CardDetailInteractor: CardDetailInteractorInterface {
}
