//
//  CardDetailWireframe.swift
//  HearthstoneLegendaryAPI
//
//  Created by 18579118 on 29.07.2020.
//  Copyright (c) 2020 18579118. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CardDetailWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(withCard card: Card) {
        let moduleViewController = CardDetailViewController()
        super.init(viewController: moduleViewController)

        let interactor = CardDetailInteractor()
        interactor.cards = card
        let presenter = CardDetailPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
        
        // setup card detail
        // service for providing url for image into few views
        DetailCardData.instance.cardImage = card.image
        DetailCardData.instance.goldCardImage = card.imageGold
    }
}

// MARK: - Extensions -

extension CardDetailWireframe: CardDetailWireframeInterface {
    func moveTo(withStringUrl url: String) {
        // route to next VC
        // TODO: may be i should route to next view in other scope (can't initiate object here)
        print("\(url)")
        let goldVC = GoldenCardViewController()
        goldVC.goldImageUrl = url
        Router.instance.route(viewController: goldVC)
    }
}
