//
//  CardsViewController.swift
//  HearthstoneLegendaryAPI
//
//  Created by 18579118 on 29.07.2020.
//  Copyright (c) 2020 18579118. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CardsCollectionViewController: UICollectionViewController {

    // MARK: - Public properties -

    var presenter: CardsPresenterProtocol!
    
    // MARK: private properties
    //private

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        // ask for configuration
        presenter.configureView()
    }
    
    override func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 1
    }
    
}

// MARK: - Extensions -

extension CardsCollectionViewController: CardsCollectionViewProtocol {
    func setView() {
        print("was setuped")
        collectionView.backgroundColor = .red
    }
    
    func setConstraints() {
        NSLayoutConstraint.activate([
            collectionView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
            collectionView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor),
            collectionView.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor),
            collectionView.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor)
        ])
    }
}
