//
//  CardsPresenter.swift
//  HearthstoneLegendaryAPI
//
//  Created by 18579118 on 29.07.2020.
//  Copyright (c) 2020 18579118. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CardsPresenter {

    // MARK: - Private properties -

    private unowned let view: CardsViewInterface
    private let interactor: CardsInteractorInterface
    private let wireframe: CardsWireframeInterface

    // MARK: - Lifecycle -

    init(view: CardsViewInterface, interactor: CardsInteractorInterface, wireframe: CardsWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension CardsPresenter: CardsPresenterInterface {
}
