//
//  CardsInterfaces.swift
//  HearthstoneLegendaryAPI
//
//  Created by 18579118 on 29.07.2020.
//  Copyright (c) 2020 18579118. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol CardsWireframeProtocol: WireframeInterface {
    func closeCurrentViewController()
}

protocol CardsCollectionViewCellProtocol : ViewInterface {
    func setViewCell()
    func setConstraintsCell()
}

protocol CardsCollectionViewProtocol: ViewInterface {
    func setView()
    func setConstraints()
}

protocol CardsPresenterProtocol: PresenterInterface {
    // prepare view to show
    func configureView()
    // when user taps at the specific card
    func viewTapped()
}

protocol CardsInteractorProtocol: InteractorInterface {
    // download the cards with API;
    // return JSON
    func fetchData() -> String
}
