//
//  AuthScreenInterfaces.swift
//  HearthstoneLegendaryAPI
//
//  Created by 18579118 on 24.08.2020.
//  Copyright (c) 2020 18579118. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol AuthScreenWireframeInterface: WireframeInterface {
    func startLoading()
    func stopLoading(with status: AuthStatus)
    func moveToCards(by className: String)
}

protocol AuthScreenViewInterface: ViewInterface {
    func setupView()
    func performAnimation()
}

protocol AuthScreenPresenterInterface: PresenterInterface {
    func authAndPrepareToShow()
    var count: Int { get }
    func configureCell(index: Int, cell: AuthScreenViewCellInterface)
    func viewTapped(by index: Int)
}

protocol AuthScreenInteractorInterface: InteractorInterface {
    func auth(completion: @escaping (AuthJSON?, AuthStatus) -> ())
    var heroes: [Hero] { get }
}

protocol AuthScreenViewCellInterface: ViewInterface {
     func setup(with text: String, imagePath: String)
}
