//
//  AuthScreenWireframe.swift
//  HearthstoneLegendaryAPI
//
//  Created by 18579118 on 24.08.2020.
//  Copyright (c) 2020 18579118. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class AuthScreenWireframe: BaseWireframe {
    
    // MARK: - Private properties -
    private enum Constants {
        static let startLoadingDuration = 1.0
        static let stopLoadingDuration = 3.0
    }
    
    // MARK: - Module setup -
    
    init() {
        let moduleViewController = AuthScreenCollectionViewController(collectionViewLayout: UICollectionViewFlowLayout())
        super.init(viewController: moduleViewController)
        
        let interactor = AuthScreenInteractor()
        let presenter = AuthScreenPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }
    
}

// MARK: - Extensions -

extension AuthScreenWireframe: AuthScreenWireframeInterface {
    func startLoading() {
        guard let sceneDelegate = UIApplication.shared.connectedScenes
            .first?.delegate as? SceneDelegate,
            let openedController = sceneDelegate.loadingWindow?.rootViewController as? LoadingViewControllerProtocol else {
                return
        }
        sceneDelegate.openLoadingWindow()
        UIView.animate(
            withDuration: Constants.startLoadingDuration,
            delay: 0,
            options: [.autoreverse, .repeat],
            animations: {
                openedController.start()
            }
        ) {
           _ in
        }
    }
    
    func stopLoading(with result: Result<AuthJSON?, AuthError>) {
        guard let sceneDelegate = UIApplication.shared.connectedScenes
            .first?.delegate as? SceneDelegate,
            let openedController = sceneDelegate.loadingWindow?.rootViewController as? LoadingViewControllerProtocol else {
                return
        }
        
        UIView.animate(
            withDuration: Constants.stopLoadingDuration,
            delay: 0,
            animations: {
                switch result {
                case .success:
                    openedController.stop()
                default:
                    openedController.stopError()
                }
            }
        ) { _ in
            switch result {
            case .success(_):
                sceneDelegate.closeLoadingWindow()
            case .failure(let authentificationError):
                print(authentificationError)
            }
        }
    }
    
    func moveToCards(by className: String) {
        let cardsWireframe = CardsWireframe(with: className)
        navigationController?.pushWireframe(cardsWireframe)
    }
}
